services:
  database:
    image: mysql:8.0
    container_name: database
    networks:
      - wp-db-network
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE_NAME}
      - MYSQL_USER=${SQL_DATABASE_USER}
      - MYSQL_PASSWORD=${SQL_DATABASE_PASSWORD}


  wordpress:
    depends_on:
      - database
    image: wordpress:6.7.2-php8.4-fpm
    container_name: wordpress
    networks:
      - wp-network
      - wp-db-network
    volumes:
      - ./wordpress:/var/www/html
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=${SQL_DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${SQL_DATABASE_PASSWORD}
      - WORDPRESS_DB_NAME=${SQL_DATABASE_NAME}


  nginx:
    image: nginx:1.15.12-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    networks:
      - wp-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl:/etc/nginx/ssl #dhparam - optional

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:8080:80" # only accessible from localhost
    networks:
      - wp-db-network

networks:
  wp-network:
    driver: bridge
  wp-db-network:
    driver: bridge  
volumes:
  mysql_data:
